version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_install:
      - pip install sphinx>=8.1.3 sphinx-rtd-theme>=3.0.2 nbsphinx>=0.9.6 pydata-sphinx-theme>=0.16.1 myst-parser>=4.0.1 sphinxcontrib-napoleon>=0.7 ipykernel>=6.29.5
    pre_build:
      - export JAX_PLATFORMS=cpu

python:
  install:
    - method: pip
      path: .

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false