# General linting settings
line-length = 100
target-version = "py310"
select = ["E", "F", "B", "I", "N", "UP", "ANN", "S", "A", "COM", "C4", "PIE", "PT", "RET", "SIM", "ARG", "ERA", "PL"]
ignore = [
    "ANN401",  # Ignore "Any" type hint errors - useful for jaxtyping
    "PYI021",  # Ignore errors related to jaxtyping Array imports/usages
    "F722",    # Ignore forward annotation error with jaxtyping Array
]

# Specific settings for jaxtyping
[lint.per-file-ignores]
"**/*.py" = ["F821"]  # Ignore undefined name errors which often occur with jaxtyping

# Typing settings
[lint.isort]
known-third-party = ["jax", "jaxtyping"]

[lint.pydocstyle]
convention = "google"